import { Buffer } from "node:buffer";
import { createHash, pbkdf2Sync, randomBytes } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { AE_CATEGORY_GROUPS, AE_CATEGORY_RELATIONSHIPS } from "./categories-ae";
import { AE_EMIRATES, AE_PLAN_SEED } from "./locations-ae";

/**
 * Generates db/seed.sql - reference data the portal cannot run without.
 *
 * Deliberately NOT inside drizzle/: wrangler treats every .sql file in the
 * migrations directory as a migration, so a regenerated seed would change the
 * checksum of something already applied.
 *
 * Written as SQL rather than executed directly because D1 has no TCP endpoint:
 * wrangler ships a file. It also means the same seed applies identically to
 * local and remote, and can be reviewed in a diff before it touches production.
 *
 * Idempotent throughout: every insert is INSERT OR IGNORE keyed on a natural
 * unique column, so re-running never duplicates and never clobbers edits made
 * in the admin panel.
 *
 * Run: pnpm seed:build && pnpm db:migrate && pnpm db:seed
 */

const out: string[] = [];
const q = (v: string | null | undefined) =>
  v === null || v === undefined ? "NULL" : `'${v.replace(/'/g, "''")}'`;
const now = "unixepoch()";

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

out.push("-- Generated by lib/db/seed/build-seed.ts. Do not edit by hand.");
out.push("PRAGMA foreign_keys = ON;");
out.push("");

/* ── Countries ──────────────────────────────────────────────────────────── */

out.push("-- Countries");
out.push(
  `INSERT OR IGNORE INTO countries (code, name, currency, dial_code, locales, default_locale, status, created_at, updated_at) VALUES
  ('ae', 'United Arab Emirates', 'AED', '+971', '["en","ar"]', 'en', 'active', ${now}, ${now}),
  ('in', 'India', 'INR', '+91', '["en"]', 'en', 'active', ${now}, ${now});`,
);
out.push("");

const AE = "(SELECT id FROM countries WHERE code = 'ae')";

/* ── Locations ──────────────────────────────────────────────────────────── */

out.push("-- Emirates");
AE_EMIRATES.forEach((e, i) => {
  out.push(
    `INSERT OR IGNORE INTO locations (country_id, parent_id, level, slug, name, sort_order, status, created_at, updated_at)
     VALUES (${AE}, NULL, 'emirate', ${q(slugify(e.name))}, ${q(e.name)}, ${i}, 'active', ${now}, ${now});`,
  );
});
out.push("");

out.push("-- Cities");
for (const e of AE_EMIRATES) {
  const parent = `(SELECT id FROM locations WHERE country_id = ${AE} AND slug = ${q(slugify(e.name))})`;
  e.cities.forEach((c, i) => {
    // City slugs can collide across emirates (both Dibba entries), so they are
    // namespaced by emirate. The unique index is (country_id, slug).
    let slug = slugify(c);
    if (AE_EMIRATES.some((o) => o !== e && o.cities.includes(c))) {
      slug = `${slugify(e.name)}-${slug}`;
    }
    out.push(
      `INSERT OR IGNORE INTO locations (country_id, parent_id, level, slug, name, sort_order, status, created_at, updated_at)
       VALUES (${AE}, ${parent}, 'city', ${q(slug)}, ${q(c)}, ${i}, 'active', ${now}, ${now});`,
    );
  });
}
out.push("");

/* ── Categories ─────────────────────────────────────────────────────────── */

// The client's list repeats a few sub-categories across groups (Advertising
// Agencies sits under both Events & Entertainment and Business Services).
// Slugs are unique per country, so the later occurrence is namespaced rather
// than dropped - nothing he sent goes missing.
const usedSlugs = new Set<string>();
const catSlug = (name: string, parent?: string) => {
  const base = slugify(name);
  if (!usedSlugs.has(base)) {
    usedSlugs.add(base);
    return base;
  }
  const scoped = `${base}-${slugify(parent ?? "other").split("-")[0]}`;
  let candidate = scoped;
  let n = 2;
  while (usedSlugs.has(candidate)) candidate = `${scoped}-${n++}`;
  usedSlugs.add(candidate);
  return candidate;
};

const subSlugByName = new Map<string, string>();
const groupSlug = new Map<(typeof AE_CATEGORY_GROUPS)[number], string>();

out.push("-- Main categories");
AE_CATEGORY_GROUPS.forEach((g, i) => {
  const slug = catSlug(g.name);
  out.push(
    `INSERT OR IGNORE INTO categories (country_id, parent_id, slug, name, sort_order, status, created_at, updated_at)
     VALUES (${AE}, NULL, ${q(slug)}, ${q(g.name)}, ${i}, 'active', ${now}, ${now});`,
  );
  groupSlug.set(g, slug);
});
out.push("");

out.push("-- Sub-categories");
for (const g of AE_CATEGORY_GROUPS) {
  const parent = `(SELECT id FROM categories WHERE country_id = ${AE} AND slug = ${q(groupSlug.get(g)!)})`;
  g.children.forEach((c, i) => {
    const slug = catSlug(c, g.name);
    // First occurrence wins for relationship lookups, which are keyed by name.
    if (!subSlugByName.has(c)) subSlugByName.set(c, slug);
    out.push(
      `INSERT OR IGNORE INTO categories (country_id, parent_id, slug, name, sort_order, status, created_at, updated_at)
       VALUES (${AE}, ${parent}, ${q(slug)}, ${q(c)}, ${i}, 'active', ${now}, ${now});`,
    );
  });
}
out.push("");

/* ── Category relationships ─────────────────────────────────────────────── */

out.push("-- Related categories (Businesses you may also need)");
let relCount = 0;
for (const [fromName, toNames] of Object.entries(AE_CATEGORY_RELATIONSHIPS)) {
  const fromSlug = subSlugByName.get(fromName);
  if (!fromSlug) {
    console.warn(`  ! relationship source not in category list: ${fromName}`);
    continue;
  }
  toNames.forEach((toName, i) => {
    const toSlug = subSlugByName.get(toName);
    if (!toSlug) {
      console.warn(`  ! relationship target not in category list: ${toName}`);
      return;
    }
    // Strongest first, stepping down, floored at 4 - ordering the client gave
    // without inventing precision he did not.
    const strength = Math.max(10 - i, 4);
    out.push(
      `INSERT OR IGNORE INTO category_relationships (category_id, related_category_id, strength) VALUES (
        (SELECT id FROM categories WHERE country_id = ${AE} AND slug = ${q(fromSlug)}),
        (SELECT id FROM categories WHERE country_id = ${AE} AND slug = ${q(toSlug)}),
        ${strength});`,
    );
    relCount++;
  });
}
out.push("");

/* ── Plans ──────────────────────────────────────────────────────────────── */

out.push("-- Plans");
for (const p of AE_PLAN_SEED) {
  const badge = "badge" in p ? (p.badge as string) : null;
  const featured = "featured" in p && p.featured ? 1 : 0;
  out.push(
    `INSERT OR IGNORE INTO plans (country_id, slug, name, price_minor, currency, billing_cycle, purpose, badge, featured, sort_order, status, created_at, updated_at)
     VALUES (${AE}, ${q(p.slug)}, ${q(p.name)}, ${p.priceMinor}, 'AED', 'monthly', ${q(p.purpose)}, ${q(badge)}, ${featured}, ${p.sortOrder}, 'active', ${now}, ${now});`,
  );
}
out.push("");

out.push("-- Plan features");
for (const p of AE_PLAN_SEED) {
  const planRef = `(SELECT id FROM plans WHERE country_id = ${AE} AND slug = ${q(p.slug)})`;
  for (const [k, v] of Object.entries(p.features)) {
    out.push(
      `INSERT OR IGNORE INTO plan_features (plan_id, feature_key, feature_value) VALUES (${planRef}, ${q(k)}, ${q(String(v))});`,
    );
  }
}
out.push("");

/* ── RBAC ───────────────────────────────────────────────────────────────── */

const PERMISSIONS: [string, string, string][] = [
  ["business.view", "listings", "See all business listings"],
  ["business.edit", "listings", "Create and edit any business listing"],
  ["business.verify", "listings", "Approve and verify listings"],
  ["business.delete", "listings", "Archive listings"],
  ["category.manage", "catalogue", "Manage categories and relationships"],
  ["location.manage", "catalogue", "Manage emirates and cities"],
  ["plan.manage", "billing", "Manage plans and feature permissions"],
  ["subscription.manage", "billing", "Activate and change subscriptions"],
  ["lead.view", "leads", "See all leads across businesses"],
  ["lead.manage", "leads", "Reassign, unlock and delete leads"],
  ["review.moderate", "content", "Publish, reject and remove reviews"],
  ["ad.manage", "content", "Manage sponsored placements"],
  ["user.manage", "access", "Manage staff accounts"],
  ["role.manage", "access", "Manage roles and permissions"],
  ["analytics.view", "insight", "See portal-wide analytics"],
];

out.push("-- Permissions");
for (const [slug, group, desc] of PERMISSIONS) {
  out.push(
    `INSERT OR IGNORE INTO permissions (slug, group_name, description) VALUES (${q(slug)}, ${q(group)}, ${q(desc)});`,
  );
}
out.push("");

const ROLES: [string, string, string, string[]][] = [
  [
    "super-admin",
    "Super Admin",
    "Full access to everything",
    PERMISSIONS.map((p) => p[0]),
  ],
  [
    "listing-manager",
    "Listing Manager",
    "Creates, edits and verifies business listings",
    ["business.view", "business.edit", "business.verify", "category.manage", "location.manage"],
  ],
  [
    "sales",
    "Sales",
    "Handles plans, subscriptions and leads",
    ["business.view", "subscription.manage", "lead.view", "lead.manage", "analytics.view"],
  ],
  [
    "content-moderator",
    "Content Moderator",
    "Moderates reviews and manages sponsored placements",
    ["business.view", "review.moderate", "ad.manage"],
  ],
  ["business-owner", "Business Owner", "Manages their own business only", []],
];

out.push("-- Roles");
for (const [slug, name, desc] of ROLES) {
  out.push(
    `INSERT OR IGNORE INTO roles (slug, name, description, is_system, created_at, updated_at) VALUES (${q(slug)}, ${q(name)}, ${q(desc)}, 1, ${now}, ${now});`,
  );
}
out.push("");

out.push("-- Role permissions");
for (const [slug, , , perms] of ROLES) {
  for (const p of perms) {
    out.push(
      `INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES (
        (SELECT id FROM roles WHERE slug = ${q(slug)}),
        (SELECT id FROM permissions WHERE slug = ${q(p)}));`,
    );
  }
}
out.push("");

/* ── First admin ────────────────────────────────────────────────────────── */

/**
 * Password hashing must match lib/auth/password.ts exactly, so a seeded
 * account can log in through the normal path. Format: pbkdf2$<iters>$<salt>$<hash>
 */
const ITERATIONS = 210_000;
function hashPassword(plain: string): string {
  const salt = randomBytes(16);
  const dk = pbkdf2Sync(plain, salt, ITERATIONS, 32, "sha256");
  // Buffer.from(...) is explicit because the Workers type definitions
  // shadow Node's Buffer, so the encoding overload of toString is not seen.
  return `pbkdf2$${ITERATIONS}$${Buffer.from(salt).toString("base64")}$${Buffer.from(dk).toString("base64")}`;
}

const adminEmail = process.env.SEED_ADMIN_EMAIL ?? "admin@brandupme.ae";

/**
 * Generated unless supplied. The resulting seed.sql carries this account's
 * password hash, which is why that file is gitignored - the repository is
 * public. Set SEED_ADMIN_PASSWORD to choose your own before running.
 */
const adminPassword =
  process.env.SEED_ADMIN_PASSWORD ?? Buffer.from(randomBytes(9)).toString("base64url");

out.push("-- First admin account");
out.push(
  `INSERT OR IGNORE INTO users (email, name, kind, status, password_hash, created_at, updated_at)
   VALUES (${q(adminEmail)}, 'BrandUpMe Admin', 'staff', 'active', ${q(hashPassword(adminPassword))}, ${now}, ${now});`,
);
out.push(
  `INSERT OR IGNORE INTO user_roles (user_id, role_id) VALUES (
    (SELECT id FROM users WHERE email = ${q(adminEmail)}),
    (SELECT id FROM roles WHERE slug = 'super-admin'));`,
);
out.push("");

mkdirSync("db", { recursive: true });
writeFileSync("db/seed.sql", out.join("\n"), "utf-8");

const subCount = AE_CATEGORY_GROUPS.reduce((n, g) => n + g.children.length, 0);
const cityCount = AE_EMIRATES.reduce((n, e) => n + e.cities.length, 0);

console.log("db/seed.sql written");
console.log(`  countries      2`);
console.log(`  emirates       ${AE_EMIRATES.length}`);
console.log(`  cities         ${cityCount}`);
console.log(`  categories     ${AE_CATEGORY_GROUPS.length} groups + ${subCount} sub`);
console.log(`  relationships  ${relCount}`);
console.log(`  plans          ${AE_PLAN_SEED.length}`);
console.log(`  permissions    ${PERMISSIONS.length}`);
console.log(`  roles          ${ROLES.length}`);
console.log("");
console.log(`  admin login    ${adminEmail}`);
console.log(`  admin password ${adminPassword}`);
console.log(
  createHash("sha256").update(adminPassword).digest("hex").slice(0, 0) +
    "  (set SEED_ADMIN_PASSWORD to choose your own before running)",
);
