/**
 * The client's UAE category list, verbatim.
 *
 * 21 main groups and their sub-categories, exactly as supplied - no additions,
 * no renaming, no merging of near-duplicates. Where the same sub-category
 * appears under two groups (Advertising Agencies is under both Events &
 * Entertainment and Business Services) it is kept in both, because slugs are
 * unique per country and the second occurrence would collide. The duplicate is
 * suffixed rather than dropped, so nothing the client sent goes missing.
 *
 * Sub-category slugs are derived, not stored here, so the list stays readable
 * and a rename is a one-line edit.
 */

export type CategoryGroup = { name: string; children: string[] };

export const AE_CATEGORY_GROUPS: CategoryGroup[] = [
  {
    name: "Business Formation & Corporate Services",
    children: [
      "Business Setup Companies",
      "Mainland Company Formation",
      "Free Zone Company Formation",
      "Offshore Company Formation",
      "PRO Services",
      "Document Clearing Services",
      "Company Liquidation",
      "Trade License Renewal",
      "Golden Visa Services",
      "Investor Visa Services",
      "Family Visa Services",
      "Emirates ID Services",
      "Business Consultancy",
      "Corporate Tax Consultancy",
      "VAT Registration & Consultancy",
      "Accounting & Bookkeeping",
      "Audit Firms",
      "Legal Consultants",
      "Law Firms",
      "Trademark Registration",
      "Intellectual Property Services",
      "Company Buy & Sale",
    ],
  },
  {
    name: "Finance & Banking",
    children: [
      "Banks",
      "Islamic Banks",
      "Insurance Companies",
      "Health Insurance",
      "Vehicle Insurance",
      "Business Insurance",
      "Financial Consultants",
      "Investment Companies",
      "Wealth Management",
      "Mortgage Consultants",
      "Business Loan Consultants",
      "Money Exchange",
    ],
  },
  {
    name: "Real Estate",
    children: [
      "Real Estate Agencies",
      "Property Developers",
      "Residential Properties",
      "Commercial Properties",
      "Villas",
      "Apartments",
      "Warehouses",
      "Office Spaces",
      "Property Management",
      "Holiday Homes",
      "Property Valuation",
      "Property Investment Consultancy",
    ],
  },
  {
    name: "Construction & Engineering",
    children: [
      "Construction Companies",
      "Civil Contractors",
      "MEP Contractors",
      "Architecture Firms",
      "Interior Designers",
      "Fit-Out Contractors",
      "HVAC Companies",
      "Plumbing Contractors",
      "Electrical Contractors",
      "Waterproofing Companies",
      "Aluminium & Glass Companies",
      "Steel Fabrication",
      "Building Materials Suppliers",
    ],
  },
  {
    name: "Manufacturing & Industrial",
    children: [
      "Food Manufacturers",
      "Beverage Manufacturers",
      "Plastic Manufacturers",
      "Packaging Manufacturers",
      "Garment Manufacturers",
      "Furniture Manufacturers",
      "Chemical Manufacturers",
      "Pharmaceutical Manufacturers",
      "Steel Manufacturers",
      "Industrial Equipment Manufacturers",
      "Machinery Manufacturers",
      "Printing & Packaging",
    ],
  },
  {
    name: "Import, Export & Trading",
    children: [
      "Import Companies",
      "Export Companies",
      "Food Stuff Trading",
      "Electronics Trading",
      "Building Material Trading",
      "General Trading",
      "Hardware Trading",
      "Textile Trading",
      "Chemical Trading",
      "Automobile Parts Trading",
      "Medical Equipment Trading",
    ],
  },
  {
    name: "Automobile",
    children: [
      "Car Rental",
      "Luxury Car Rental",
      "Used Car Dealers",
      "New Car Dealers",
      "Auto Workshops",
      "Auto Spare Parts",
      "Car Accessories",
      "Car Wash",
      "Vehicle Recovery",
      "Vehicle Inspection",
      "Tyre Dealers",
      "Battery Dealers",
    ],
  },
  {
    name: "Logistics & Transportation",
    children: [
      "Logistics Companies",
      "Freight Forwarding",
      "Cargo Services",
      "Shipping Companies",
      "Air Freight",
      "Sea Freight",
      "Land Transport",
      "Movers & Packers",
      "Warehouse Services",
      "Courier Services",
    ],
  },
  {
    name: "Travel & Tourism",
    children: [
      "Tour Operators",
      "Travel Agencies",
      "Visa Consultants",
      "Hotel Booking",
      "Holiday Packages",
      "Desert Safari",
      "Yacht Rental",
      "Cruise Booking",
      "Airport Transfer",
      "Travel Insurance",
    ],
  },
  {
    name: "Hotels, Restaurants & Hospitality",
    children: [
      "Hotels",
      "Resorts",
      "Restaurants",
      "Cafes",
      "Catering Services",
      "Cloud Kitchens",
      "Bakery",
      "Fast Food",
      "Fine Dining",
      "Banquet Halls",
    ],
  },
  {
    name: "Healthcare & Medical",
    children: [
      "Hospitals",
      "Medical Clinics",
      "Dental Clinics",
      "Diagnostic Centres",
      "Pharmacies",
      "Physiotherapy",
      "Home Healthcare",
      "Medical Equipment Suppliers",
      "Laboratories",
      "Ambulance Services",
    ],
  },
  {
    name: "Beauty, Wellness & Fitness",
    children: [
      "Beauty Salons",
      "Gents Salons",
      "Spas",
      "Gyms",
      "Fitness Centres",
      "Yoga Centres",
      "Personal Trainers",
      "Cosmetic Clinics",
      "Nutrition Consultants",
    ],
  },
  {
    name: "Education & Training",
    children: [
      "Schools",
      "Universities",
      "Colleges",
      "Nursery Schools",
      "Coaching Centres",
      "Language Institutes",
      "Computer Training",
      "Professional Training",
      "Online Education",
    ],
  },
  {
    name: "HR & Recruitment",
    children: [
      "HR Consultancy",
      "Recruitment Agencies",
      "Overseas Recruitment",
      "Staff Outsourcing",
      "Payroll Services",
      "Corporate Training",
    ],
  },
  {
    name: "Information Technology",
    children: [
      "IT Companies",
      "Software Development",
      "Website Development",
      "Mobile App Development",
      "ERP Solutions",
      "CRM Solutions",
      "AI Automation",
      "Cyber Security",
      "Cloud Solutions",
      "Digital Marketing",
      "SEO Services",
      "Social Media Marketing",
      "Graphic Design",
      "Video Production",
    ],
  },
  {
    name: "Home & Maintenance Services",
    children: [
      "Cleaning Companies",
      "Pest Control",
      "Home Maintenance",
      "AC Repair",
      "Appliance Repair",
      "Plumbing Services",
      "Electrical Services",
      "Painting Contractors",
      "Handyman Services",
      "Laundry Services",
    ],
  },
  {
    name: "Retail & Shopping",
    children: [
      "Supermarkets",
      "Hypermarkets",
      "Electronics Stores",
      "Furniture Stores",
      "Fashion Stores",
      "Jewellery Stores",
      "Gift Shops",
      "Mobile Stores",
      "Computer Stores",
      "Sports Equipment",
    ],
  },
  {
    name: "Events & Entertainment",
    children: [
      "Event Management",
      "Wedding Planners",
      "Exhibition Organizers",
      "Photography",
      "Videography",
      "DJ Services",
      "Sound & Lighting",
      "Advertising Agencies",
      "Printing Services",
      "Exhibition Stand Contractors",
    ],
  },
  {
    name: "Business Services",
    children: [
      "Advertising Agencies",
      "Branding Agencies",
      "Printing Press",
      "Signage Companies",
      "Promotional Gifts",
      "Call Centre Services",
      "BPO Services",
      "Translation Services",
      "Public Relations",
      "Market Research",
    ],
  },
  {
    name: "Government & Public Services",
    children: [
      "Government Services",
      "Municipality Services",
      "Chamber of Commerce",
      "Economic Department Services",
      "Immigration Services",
      "Notary Services",
    ],
  },
  {
    name: "Others",
    children: [
      "Pet Care",
      "NGOs",
      "Security Services",
      "Facility Management",
      "Franchise Opportunities",
      "Business Networking",
      "Miscellaneous Services",
    ],
  },
];

/**
 * "Businesses you may also need", from the client's relationship matrix.
 *
 * Keyed by sub-category name so the seed can resolve ids. Strengths follow his
 * worked example (cleaning -> recruitment 10, -> digital marketing 3): the
 * first entry is the strongest and each subsequent one steps down, floored at
 * 4, so ordering is meaningful without inventing precision he did not give.
 */
export const AE_CATEGORY_RELATIONSHIPS: Record<string, string[]> = {
  "Business Setup Companies": [
    "PRO Services",
    "Banks",
    "Accounting & Bookkeeping",
    "Corporate Tax Consultancy",
    "Office Spaces",
    "Legal Consultants",
    "Trademark Registration",
    "HR Consultancy",
    "Website Development",
    "Digital Marketing",
  ],
  "Cleaning Companies": [
    "Recruitment Agencies",
    "Facility Management",
    "Pest Control",
    "Laundry Services",
    "Land Transport",
    "Business Insurance",
    "HR Consultancy",
    "Digital Marketing",
  ],
  Restaurants: [
    "Food Stuff Trading",
    "Catering Services",
    "Packaging Manufacturers",
    "Cleaning Companies",
    "Pest Control",
    "Interior Designers",
    "Courier Services",
    "Digital Marketing",
  ],
  "Real Estate Agencies": [
    "Movers & Packers",
    "Interior Designers",
    "Cleaning Companies",
    "Home Maintenance",
    "Business Insurance",
    "Furniture Stores",
    "Legal Consultants",
  ],
  Hospitals: [
    "Medical Equipment Suppliers",
    "Insurance Companies",
    "Recruitment Agencies",
    "Laboratories",
    "Ambulance Services",
    "Pharmacies",
    "Cleaning Companies",
  ],
  "Construction Companies": [
    "Building Materials Suppliers",
    "Steel Fabrication",
    "Civil Contractors",
    "Staff Outsourcing",
    "Logistics Companies",
    "Architecture Firms",
    "Interior Designers",
    "Business Insurance",
  ],
  "Food Manufacturers": [
    "Packaging Manufacturers",
    "Logistics Companies",
    "Warehouse Services",
    "Industrial Equipment Manufacturers",
    "Recruitment Agencies",
    "Printing & Packaging",
  ],
  "Tour Operators": [
    "Hotels",
    "Car Rental",
    "Visa Consultants",
    "Travel Agencies",
    "Money Exchange",
    "Travel Insurance",
    "Event Management",
    "Restaurants",
  ],
  "Used Car Dealers": [
    "Auto Spare Parts",
    "Vehicle Insurance",
    "Car Rental",
    "Vehicle Recovery",
    "Auto Workshops",
    "Logistics Companies",
  ],
  "IT Companies": [
    "Cyber Security",
    "Cloud Solutions",
    "Website Development",
    "Digital Marketing",
    "ERP Solutions",
    "Electronics Trading",
    "AI Automation",
  ],
  Hotels: [
    "Laundry Services",
    "Food Stuff Trading",
    "Recruitment Agencies",
    "Security Services",
    "Tour Operators",
    "Car Rental",
  ],
  Schools: [
    "Fashion Stores",
    "Furniture Stores",
    "Land Transport",
    "Security Services",
    "Printing Services",
    "IT Companies",
  ],
  "Supermarkets": [
    "Food Stuff Trading",
    "Packaging Manufacturers",
    "Digital Marketing",
    "Logistics Companies",
    "Security Services",
  ],
};
